general: {}
addon:
  balance_monitor: true
  deposit_monitor: true
query:
  bearer_token: ''
  auth_link: ''
  session_id: ''
record_csv:
  csv_file_path: ../data/records/query_data.csv
  query_interval: 1200
email:
  enable: false
  sender_email: mail@example.com
  sender_name: root
  smtp_server: smtp.example.com
  smtp_port: 587
  smtp_user: mail@example.com
  smtp_password: <passwd>
pushplus:
  enable: false
  token: <token>
  topic: ''
  channel: wechat
  max_attempts: 3
balance_monitor:
  to_emails: mail@example.com
  threshold:
    water_balance: 5
    electricity_balance: 5
    air_conditioner_balance: 8
